inherit_from: .rubocop_todo.yml

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
  
Style/ModuleFunction:
  Enabled: false
  
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
